<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="NodaTime" Version="3.3.3" />
    <PackageVersion Include="NodaTime.Serialization.SystemTextJson" Version="1.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <!-- Test-only packages. -->
  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="NodaTime.Testing" Version="3.3.3" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="PublicApiGenerator" Version="11.5.4" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>

</Project>
